### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pjstarrusa** [shadowystupidcoder/Solana-Dexscreener-Moonshot-Sniper#1]
It runs. It asks the questions. I am able to add my private key and the purchase amounts. I tried a custom rpc and the default rpc, neither are working. After hitting enter on the rpc entry it just hangs. Nothing happens.

What is the port that should be opened through the firewall? Although, I disabled the firewall and still have the same problem.

**Comment by ppegu** [comment]
contact me https://t.me/ppegu i got working one developed in rust.

**Comment by shadowystupidcoder** [comment]
> It runs. It asks the questions. I am able to add my private key and the purchase amounts. I tried a custom rpc and the default rpc, neither are working. After hitting enter on the rpc entry it just hangs. Nothing happens.
> 
> What is the port that should be opened through the firewall? Although, I disabled the firewall and still have the same problem.

you dont need to open any ports and i suggest you do not ever do that. as long as your browser works then node.js should work as they both use port 443 for https.

I just forgot to add status update messages, if you check your wallet the bot should be running and actively buying tokens. Ill update this later today with status update messages so it doesnt look like it hangs.
